---
- name: update pacman database
  tags: pacman
  pacman:
    update_cache: yes
    state: present

- name: upgrade packages
  tags: pacman
  pacman:
    upgrade: yes
    update_cache: yes

- name: install required packages
  tags: pacman
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - curl
    - rsync
    - htop
    - openssh
    - openssl
    - bash-completion
