---
- name: install virtualbox utils for guest
  tags: virtualbox
  pacman:
    name: "virtualbox-guest-modules-arch,virtualbox-guest-utils"
    state: present

- name: enable virtualbox service for guest
  tags: virtualbox
  service:
    name: vboxservice
    enabled: yes
